name: starthack2024
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - flask
  - flask_cors
  - pip:
      - geemap
      - ee
      - folium
      - python-dotenv
      - PyCRS
      - werkzeug
